version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures hot-reloading catches file saves on all operating systems
      - REACT_APP_ENVIRONMENT=dev # Set the environment variable for the React app
